# Generated by Django 4.2.1 on 2023-05-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=100)),
                ('is_published', models.CharField(choices=[('TRUE', 'Продается'), ('FALSE', 'Продано')], default='FALSE', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
